### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by swashdev** [clangen/homebrew-musikcube#4]
When attempting to install musikcube via homebrew (on Ubuntu), this error comes up:

    In file included from /tmp/musikcube-20190508-10920-1oksu8n/musikcube-0.65.0/src/cor/support/Auddio.cpp:38:0:
    /tmp/musikcube-20190508-10920-1oksu8n/musikcube-0.65.0/src/core/sdk/HttpClient.h:35:23: fatal error: curl/curl.h: No such file or directory
    compilation terminated.

etcetera.

Not knowing how homebrew works I was slightly stumped, but on a hunch I tried `brew install curl` and that installed the dependency I was missing and installation subsequently succeeded.  Someone probably just forgot to list curl as a dependency, or it accidentally got deleted, or something.

**Comment by clangen** [comment]
Whoa. Can't believe this was broken for so long. 

Fixed in https://github.com/clangen/homebrew-musikcube/commit/e0dbe62ad97f7fc7d9e6804730b29518ef501616

Thanks for the report!
