### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by singulararmchair** [clangen/homebrew-musikcube#6]
Same error that's been reported before.

> cmake -DCMAKE_BUILD_TYPE=Release -DHOMEBREW_PREFIX=/usr/local -DCMAKE_INSTAL
> ==> make
> Last 15 lines from /Users/x/Library/Logs/Homebrew/musikcube/02.make:
> [ 25%] Building CXX object src/core/CMakeFiles/musikcore.dir/runtime/MessageQueue.cpp.o
> [ 25%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/Auddio.cpp.o
> [ 25%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/Duration.cpp.o
> [ 26%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/Common.cpp.o
> [ 26%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/LastFm.cpp.o
> [ 26%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/Playback.cpp.o
> [ 27%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/Preferences.cpp.o
> [ 27%] Building CXX object src/core/CMakeFiles/musikcore.dir/support/PreferenceKeys.cpp.o
> [ 27%] Building C object src/core/CMakeFiles/musikcore.dir/__/3rdparty/src/sqlite/sqlite3.c.o
> [ 28%] Building C object src/core/CMakeFiles/musikcore.dir/__/3rdparty/src/kiss_fft.c.o
> [ 28%] Building C object src/core/CMakeFiles/musikcore.dir/__/3rdparty/src/kiss_fftr.c.o
> [ 28%] Building C object src/core/CMakeFiles/musikcore.dir/__/3rdparty/src/md5.c.o
> [ 29%] Linking CXX shared library ../../bin/libmusikcore.dylib
> [ 29%] Built target musikcore
> make: *** [all] Error 2

OS: High Sierra 10.13.6
I've already run `brew doctor`, `brew upgrade`, `brew cleanup`, to no avail.
Weirdly I have a second computer with the same OS and it installed just fine.

**Comment by hussein-esmail7** [comment]
I also have this issue, but my percentages are all between 73% and 77%.

**Comment by clangen** [comment]
I just released version 0.93.1, which should correct this build error. Please re-open if you still have issues, and make sure to attach a full log if possible. The location of the log file is called out right below the cmake command. For example, in the output above it's `Last 15 lines from /Users/x/Library/Logs/Homebrew/musikcube/02.make:`
